#!/usr/bin/env bash
# Automatical installs nginx server and configures it

apt-get update
apt-get install -y nginx
ufw enable -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > ~/var/www/html/index.html
service nginx restart
