#!/usr/bin/env bash
# install nginx server
# confiure the nginx server for redirection

apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
chmod 600 /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
sed -i '46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
