#!/usr/bin/env bash
# Installs and setup haproxy on my lb-01 server

apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 29434-web-01 44.200.48.169:80 check
   server 29434-web-02 3.238.85.27:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart