#!/usr/bin/env bash
# set up load balancer
apt update
apt install -y haproxy
echo "\
frontend http
   bind *:80
   default_backend web-backend
backend web-backend
   balance roundrobin
   server web-01 3.235.178.105:80 check
   server web-02 3.235.75.111:80 check
" | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
