#!/usr/bin/env bash
# This script to compress my sqldump file
#+ and save it in another physical location.

mysqldump --all-databases -u root --password="$1" > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -cvzf "$file_name" backup.sql
