#!/usr/bin/env bash
# using ping ICMP to make sure that a network device remains online or to troubleshoot issues on the network.

args=("$@")

if [ -z "${args[0]}" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    sudo ping -c 5 "${args[0]}"
fi