#!/usr/bin/env bash
#Trying to figure out what’s keeping your Ubuntu container’s Nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
