#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:

    # display hours from 0 to 12
    # display minutes from 1 to 59

hr=0

while [ $hr -lt 13 ]
do
    echo "Hour: $hr"
    min=1
    while [ $min -lt 60 ]
    do
        echo "$min"
        (( min++ ))
    done
    (( hr++ ))
done
