#!/usr/bin/env bash
# configure a firewall that allows
#+ http, https and ssh connection on tcp.

sudo apt-get install ufw
sed -i "s/IPV6=.*/IPV6=yes" /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
